name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7 

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt
        run: terraform fmt 

      - name: Terraform validate
        run: terraform validate
