name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize Packer
        run: |
          packer init .

      - name: Run Packer fmt check
        run: |
          packer fmt -check .

  packer-validate:
    runs-on: ubuntu-latest
    needs: packer-format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize Packer
        run: |
          packer init .

      - name: Run Packer validate
        run: |
          packer validate .
